import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import familyRouter from "./family";
import propertiesRouter from "./properties";
import choresRouter from "./chores";
import groceryRouter from "./grocery";
import mealsRouter from "./meals";
import todosRouter from "./todos";
import maintenanceRouter from "./maintenance";
import aiRouter from "./ai";
import workoutsRouter from "./workouts";
import pushTokensRouter from "./pushTokens";
import webPushRouter from "./webPush";
import meRouter from "./me";
import householdRouter from "./household";
import onboardingRouter from "./onboarding";
import recipesRouter from "./recipes";
import peopleRouter from "./people";
import notificationPreferencesRouter from "./notificationPreferences";
import storesRouter from "./stores";
import { requireApprovedHousehold } from "../middlewares/requireApprovedHousehold";

const router: IRouter = Router();

router.use(healthRouter);
router.use(meRouter);
router.use(requireApprovedHousehold);
router.use(householdRouter);
router.use(onboardingRouter);
router.use(dashboardRouter);
router.use(familyRouter);
router.use(propertiesRouter);
router.use(choresRouter);
router.use(groceryRouter);
router.use(storesRouter);
router.use(mealsRouter);
router.use(todosRouter);
router.use(maintenanceRouter);
router.use(aiRouter);
router.use(workoutsRouter);
router.use(pushTokensRouter);
router.use(webPushRouter);
router.use(recipesRouter);
router.use(peopleRouter);
router.use(notificationPreferencesRouter);

export default router;
