// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homehub-meal-week/Current.tsx": () => import("../components/mockups/homehub-meal-week/Current.tsx"),
  "./components/mockups/homehub-meal-week/KidsFridgePrintable.tsx": () => import("../components/mockups/homehub-meal-week/KidsFridgePrintable.tsx"),
  "./components/mockups/homehub-meal-week/MobileGroceries.tsx": () => import("../components/mockups/homehub-meal-week/MobileGroceries.tsx"),
  "./components/mockups/homehub-meal-week/MobileMeals.tsx": () => import("../components/mockups/homehub-meal-week/MobileMeals.tsx"),
  "./components/mockups/homehub-meal-week/Refined.tsx": () => import("../components/mockups/homehub-meal-week/Refined.tsx"),
  "./components/mockups/homehub-meal-week/WithAICoach.tsx": () => import("../components/mockups/homehub-meal-week/WithAICoach.tsx"),
  "./components/mockups/homehub-workouts/Current.tsx": () => import("../components/mockups/homehub-workouts/Current.tsx")
};
