ALTER TABLE "wallet_transactions"
  ADD COLUMN IF NOT EXISTS "occurrence_key" text;

-- Existing completed rewards represent the completion currently stored on
-- their chore. The millisecond epoch is also the key generated by the API.
UPDATE "wallet_transactions" AS wt
SET "occurrence_key" = COALESCE(
  floor(extract(epoch FROM c."completed_at") * 1000)::bigint::text,
  'legacy-' || wt."id"::text
)
FROM "chores" AS c
WHERE wt."chore_id" = c."id"
  AND wt."type" = 'chore_reward'
  AND wt."occurrence_key" IS NULL;

ALTER TABLE "wallet_transactions"
  DROP CONSTRAINT IF EXISTS "wallet_transactions_chore_reward_check";

ALTER TABLE "wallet_transactions"
  DROP CONSTRAINT IF EXISTS "wallet_transactions_chore_reward_occurrence_check";

ALTER TABLE "wallet_transactions"
  ADD CONSTRAINT "wallet_transactions_chore_reward_occurrence_check"
  CHECK (
    ("type" = 'chore_reward' AND "chore_id" IS NOT NULL
      AND "occurrence_key" IS NOT NULL AND "amount_cents" > 0)
    OR ("type" <> 'chore_reward' AND "chore_id" IS NULL
      AND "occurrence_key" IS NULL)
  );

DROP INDEX IF EXISTS "wallet_transactions_chore_reward_unique";
CREATE UNIQUE INDEX IF NOT EXISTS "wallet_transactions_chore_occurrence_unique"
  ON "wallet_transactions" ("chore_id", "occurrence_key")
  WHERE "type" = 'chore_reward';