export interface AppTheme {
  id: string;
  name: string;
  emoji: string;
  isDark: boolean;
  // Core surfaces
  primary: string;
  primaryForeground: string;
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  secondary: string;
  secondaryForeground: string;
  muted: string;
  mutedForeground: string;
  border: string;
  // Status
  danger: string;
  warning: string;
  success: string;
  // Legacy aliases kept for compatibility
  accent: string;
  accentForeground: string;
  tint: string;
  input: string;
  destructive: string;
  destructiveForeground: string;
  text: string;
  radius: number;
}

export const THEMES: AppTheme[] = [
  {
    id: 'sage',
    name: 'Sage',
    emoji: '🌿',
    isDark: false,
    primary: '#2D6A4F',
    primaryForeground: '#FFFFFF',
    background: '#FAFAF7',
    foreground: '#1C1917',
    card: '#FFFFFF',
    cardForeground: '#1C1917',
    secondary: '#F5F0E8',
    secondaryForeground: '#1C1917',
    muted: '#F0EBE3',
    mutedForeground: '#78716C',
    border: '#E5DDD3',
    danger: '#EF4444',
    warning: '#E9A826',
    success: '#2D6A4F',
    accent: '#E9C46A',
    accentForeground: '#1C1917',
    tint: '#2D6A4F',
    input: '#E5DDD3',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    text: '#1C1917',
    radius: 12,
  },
  {
    id: 'ocean',
    name: 'Ocean',
    emoji: '🌊',
    isDark: false,
    primary: '#0077B6',
    primaryForeground: '#FFFFFF',
    background: '#F0F7FF',
    foreground: '#0D1B2A',
    card: '#FFFFFF',
    cardForeground: '#0D1B2A',
    secondary: '#E0F0FA',
    secondaryForeground: '#0D1B2A',
    muted: '#D0E8F5',
    mutedForeground: '#4A7A95',
    border: '#B0D0E8',
    danger: '#EF4444',
    warning: '#F59E0B',
    success: '#059669',
    accent: '#48CAE4',
    accentForeground: '#0D1B2A',
    tint: '#0077B6',
    input: '#B0D0E8',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    text: '#0D1B2A',
    radius: 12,
  },
  {
    id: 'sunset',
    name: 'Sunset',
    emoji: '🌅',
    isDark: false,
    primary: '#E76F51',
    primaryForeground: '#FFFFFF',
    background: '#FFFBF5',
    foreground: '#1A0F08',
    card: '#FFFFFF',
    cardForeground: '#1A0F08',
    secondary: '#FFF0E6',
    secondaryForeground: '#1A0F08',
    muted: '#FFE5CC',
    mutedForeground: '#8A5A3E',
    border: '#F5C9A5',
    danger: '#DC2626',
    warning: '#D97706',
    success: '#059669',
    accent: '#F4A261',
    accentForeground: '#1A0F08',
    tint: '#E76F51',
    input: '#F5C9A5',
    destructive: '#DC2626',
    destructiveForeground: '#FFFFFF',
    text: '#1A0F08',
    radius: 14,
  },
  {
    id: 'berry',
    name: 'Berry',
    emoji: '🫐',
    isDark: false,
    primary: '#7C3AED',
    primaryForeground: '#FFFFFF',
    background: '#FAF8FF',
    foreground: '#1A1030',
    card: '#FFFFFF',
    cardForeground: '#1A1030',
    secondary: '#F0EBFF',
    secondaryForeground: '#1A1030',
    muted: '#E8DEFF',
    mutedForeground: '#6B5B9A',
    border: '#D0BBFF',
    danger: '#EF4444',
    warning: '#F59E0B',
    success: '#059669',
    accent: '#A78BFA',
    accentForeground: '#1A1030',
    tint: '#7C3AED',
    input: '#D0BBFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    text: '#1A1030',
    radius: 16,
  },
  {
    id: 'rose',
    name: 'Rose',
    emoji: '🌸',
    isDark: false,
    primary: '#E11D48',
    primaryForeground: '#FFFFFF',
    background: '#FFF5F7',
    foreground: '#1A0811',
    card: '#FFFFFF',
    cardForeground: '#1A0811',
    secondary: '#FFE4EC',
    secondaryForeground: '#1A0811',
    muted: '#FFD0DF',
    mutedForeground: '#9B4A64',
    border: '#F9A8C0',
    danger: '#DC2626',
    warning: '#F59E0B',
    success: '#059669',
    accent: '#FB7185',
    accentForeground: '#1A0811',
    tint: '#E11D48',
    input: '#F9A8C0',
    destructive: '#DC2626',
    destructiveForeground: '#FFFFFF',
    text: '#1A0811',
    radius: 18,
  },
  {
    id: 'midnight',
    name: 'Midnight',
    emoji: '🌙',
    isDark: true,
    primary: '#38BDF8',
    primaryForeground: '#0A0F1E',
    background: '#0A0F1E',
    foreground: '#E2E8F0',
    card: '#131929',
    cardForeground: '#E2E8F0',
    secondary: '#1A2540',
    secondaryForeground: '#E2E8F0',
    muted: '#162038',
    mutedForeground: '#64748B',
    border: '#1E2F50',
    danger: '#F87171',
    warning: '#FBBF24',
    success: '#34D399',
    accent: '#7DD3FC',
    accentForeground: '#0A0F1E',
    tint: '#38BDF8',
    input: '#1E2F50',
    destructive: '#F87171',
    destructiveForeground: '#0A0F1E',
    text: '#E2E8F0',
    radius: 12,
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    emoji: '✨',
    isDark: true,
    primary: '#F59E0B',
    primaryForeground: '#111117',
    background: '#111117',
    foreground: '#F1F0EE',
    card: '#1C1C24',
    cardForeground: '#F1F0EE',
    secondary: '#25252F',
    secondaryForeground: '#F1F0EE',
    muted: '#1F1F28',
    mutedForeground: '#71717A',
    border: '#2D2D38',
    danger: '#F87171',
    warning: '#FCD34D',
    success: '#34D399',
    accent: '#FCD34D',
    accentForeground: '#111117',
    tint: '#F59E0B',
    input: '#2D2D38',
    destructive: '#F87171',
    destructiveForeground: '#111117',
    text: '#F1F0EE',
    radius: 10,
  },
  {
    id: 'forest',
    name: 'Forest',
    emoji: '🌲',
    isDark: true,
    primary: '#10B981',
    primaryForeground: '#022C22',
    background: '#0D1A13',
    foreground: '#D1FAE5',
    card: '#142018',
    cardForeground: '#D1FAE5',
    secondary: '#1A2E22',
    secondaryForeground: '#D1FAE5',
    muted: '#162619',
    mutedForeground: '#52867A',
    border: '#1E3828',
    danger: '#F87171',
    warning: '#FBBF24',
    success: '#34D399',
    accent: '#6EE7B7',
    accentForeground: '#022C22',
    tint: '#10B981',
    input: '#1E3828',
    destructive: '#F87171',
    destructiveForeground: '#022C22',
    text: '#D1FAE5',
    radius: 12,
  },
];

export const DEFAULT_THEME_ID = 'sage';
export const getTheme = (id: string): AppTheme =>
  THEMES.find((t) => t.id === id) ?? THEMES[0];
